- name: install c dev tools
  become: yes
  package:
    name: ["base-devel" ]
    state: present
  tags: ["install", "basic"]

- name : install arch specific tools
  become: yes
  package:
    state: present
    name: 
      - "nitrogen"
      - "picom"
      - "ttf-hanazono"
      - "volumeicon"
      - "pavucontrol"
      - "pcmanfm"
      - "xorg-xkill"
      - "arc-gtk-theme"
      - "lxappearance"
      - "archlinux-wallpaper"
      - "polkit"
  tags: ["install", "basic"]

- name : install tools for aur
  become: yes
  yay:
    state: present
    name: 
      - "pamac-aur"
  tags: ["install", "basic"]
