- name: Install neovim 
  become: yes
  package:
    name: ["neovim"]
    state: present
  tags: ["install", "neovim"]

- name: Install Vim plug
  shell: "curl -fLo {{ lookup('env', 'HOME') }}/.config/local/share/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  tags: ["install", "neovim"]

- name: Install plugins
  shell: nvim --headless +PlugInstall +qa
  tags: ["install", "neovim"]
